pip install 'uvicorn[standard]' --break-system-packages
pip install python-multipart --break-system-packages
pip install 'python-jose[cryptography]' --break-system-packages
pip install 'passlib[bcrypt]' --break-system-packages
pip install authlib --break-system-packages
pip install itsdangerous --break-system-packages
pip install motor==2.5.1 --break-system-packages
pip install 'pydantic[email]' --break-system-packages
pip install asyncio --break-system-packages
pip install httpx --break-system-packages
pip install "fastapi[standard]" --break-system-packages
pip install websockets --break-system-packages
pip install slowapi --break-system-packages